echo build windows...
dotnet publish -c Release -r win10-x64
echo windows done, build OSX...
dotnet publish -c Release -r osx.10.12-x64
echo OSX done, build ubuntu 16.10...
dotnet publish -c Release -r ubuntu.16.10-x64
echo all builds done
